1632: Workload Report add invoicing rate
itk-dev/economics pull request #129
Opened 2024-06-10 12:28 UTC by jeppekroghitk

- **added navigation option for Workload report**
- **added workload report controller**
- **added workload formtype formtypedata and service file**
- **Added worker entity for storing workload value**
- **Changes to worker entity**
- **Further worker changes and added mock worker data**
- **Added workload service method to gather worker worklog data + template to render data**
- **Added CRUD for new worker entity**
- **renamed workload report template file and made template fit workload data**
- **renamed mode for workload controller to reflect translations**
- **Modified workload entities to reflect report needs**
- **Added worklog repo method to select worklogs between dates on worker**
- **Added datetimehelper service to help working with dates and weeks**
- **modified workload report service to get data split into weeks**
- **Added translations for workload report**
- **Adding week and month view, and taking a more generalized approach to fetching data**
- **Modified workload models to fit needs and added additional translations**
- **Added viewmode to workload report view**
- **Modified workload report twig to fit more generalized approach**
- **Moved calculation of logged hours percentage into seperate function for readability**
- **coding standards**
- **coding standards**
- **updated changelog**
- **added migration for worker and added tags and planhours to issue**
- **Modified fixtures to randomize started datetime of worklogs within the current year**
- **Improved the state of worker crud**
- **Added preselected default service provider**
- **taking lunch break into consideration**
- **Clarifying workload is defined all inclusive**
- **Added multiple workers, and split worklogs between them randomly**
- **Added trace of wrongly added hours_remaining on issue entity**
- **Removed unique requirement for workload on Worker entity**
- **looping period for headers only once**
- **Cleaned up in workload report template**
- **Added translations**
- **coding standards + generated documentation for service and helper method**
- **coding standards**
- **coding standards**
- **coding standards**
- **Removed wrongly placed unique index from workload migration**
- **re-added hours_remaining that was wrongly removed**
- **Messed up some migrations**
- **Added new migration to properly fix earlier migration changes**
- **Added a proposition of how to sync workers via worklog sync**
- **coding standards**
- **trying to fix php unit test error**
- **coding standards + undid github action fix**
- **moved worker-adding code above flush**
- **added active period highlight in table, and scroll to active period**
- **Restored correct changelog version links**
- **Added missing param types in worklogRepository**
- **Rolled back migrations and created a new one**
- **added .idea/ folder to gitignore**
- **Removed unneccessary doc comment**
- **Corrected doc comment**
- **updated comment**
- **added is_billable to project entity**

#### Link to ticket

Please add a link to the ticket being addressed by this change.

#### Description

Please include a short description of the suggested change and the reasoning behind the approach you have chosen.

#### Screenshot of the result

If your change affects the user interface you should include a screenshot of the result with the pull request.

#### Checklist

- [ ] My code is covered by test cases.
- [ ] My code passes our test (all our tests).
- [ ] My code passes our static analysis suite.
- [ ] My code passes our continuous integration process.

2024-06-25 11:32 UTC, tuj requested changes

2024-07-03 11:03 UTC, tuj requested changes

2024-07-03 11:03 UTC, tuj commented on src/Form/WorkloadReportType.php
> +            ->add('viewPeriodType')
remove this line
it is added again below

2024-07-03 11:03 UTC, tuj commented on src/Model/Invoices/ProjectFilterData.php
> +    public ?bool $is_billable = null;
isBillable

2024-07-03 11:03 UTC, tuj commented on src/Service/WorkloadReportService.php
> +    public function getViewPeriodTypes(): array
Is this necessary after change to enum and EnumType for forms?

2024-07-03 11:04 UTC, tuj commented on translations/messages.da.yaml
> +WorkloadReportPeriodTypeEnum:
we should use snake_case for yaml files
workload_report_period_type_enum

2024-07-04 08:08 UTC, jeppekroghitk commented on src/Enum/BillableKindsEnumType.php
> +class BillableKindsEnumType extends Type
It seems to be necessary. I don't think Doctrine understands PHP enums natively yet.
I might be wrong, but i can't get it to work otherwise.

2024-07-04 11:12 UTC, tuj requested changes

2024-07-04 11:12 UTC, tuj commented on src/Repository/WorklogRepository.php
> +    public function findBillableWorklogsByWorkerAndDateRange(string $worker, mixed $dateFrom, mixed $dateTo)
missing return type

2024-07-04 11:12 UTC, tuj commented on src/Repository/WorklogRepository.php
> +    public function findBillableWorklogsByWorkerAndDateRange(string $worker, mixed $dateFrom, mixed $dateTo)
also I am not a fan of mixed parameter types :)

2024-07-30 05:51 UTC, tuj requested changes

2024-07-30 05:51 UTC, tuj commented on src/Repository/WorklogRepository.php
> +                'date_from' => $dateFrom,
camelCase instead of snake_case

2024-07-30 05:51 UTC, tuj commented on src/Controller/ProjectController.php
> +    #[Route('/{id}/isBillable', name: 'app_project_isBillable', methods: ['POST'])]
app_project_isBillable -> app_project_is_billable

2024-07-30 09:56 UTC, tuj approved these changes

2024-07-31 06:20 UTC, merged